### PR TITLE
Added entity factory. 

### LINKED ISSUE #3: Adding Entities:
Make factories for:
- [ ] Player
- [ ] Rock
- [ ] Bomb
- [ ] Pickup

### PR DESCRIPTION
**Pull request by eldarht**
TODO: create entity instances and add data to components

### CODE REVIEW

**Comment by eldarht** [comment]
I am not sure how we want to use the assetManager so i don't know how to finish #3. 
The creation of each Entity is currently done in the EntityFactory, as the specific entities do not implement Entity. I guess they would need each their Factory if they were to be implemented as each their class/file, or as a wrapper that the factory unwraps.

**Comment by DeimosA** [comment]
We need to decide on style of implementing factories: package level or companion object @skykanin 

I've implemented some asset manager stuff in #32 

Do entities have any non-default properties other than position and texture region?

Entity factory could be made without engine as a dependency, but would have to take in an emptyEntity: Entity
Would look something like
```engine.addEntity(EntityFactory(engine.createEntity(), type, position, texture))```
Not shure what is the best approach here
Not that we're doing testability, but decoupling the factory from the engine would help

**Comment by skykanin** [comment]
I can't think of any other default properties entities would have other than position and texture region. I think this ` engine.addEntity(EntityFactory(engine.createEntity(), type, position, texture))` looks fine to me.

**Review by skykanin — APPROVED** [review]
This looks good to me, we probably won't be using pickup entities at this point, but that's fine.

**Comment by eldarht** [comment]
Should we update the map to take context instead of assetManager?

**Comment by DeimosA** [comment]
If it's just the one thing it doesn't really matter much. Just makes the map dependent on more stuff

**Pull request merged**
